image: node:latest

cache:
  paths:
   - backend/node_modules/

before_script:
  - cd backend
  - npm install
  
stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo "Running tests"

build:
  stage: build
  script:
    - echo "Building the app"
    

deploy_develop:
  stage: deploy
  script:
    - echo "Deploy to develop server"
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir "${HOME}/.ssh"
    - cd "${HOME}/.ssh"
    - echo "${SSH_PRIVATE_KEY}" > id_rsa
    - chmod 700 id_rsa
    - echo "${SSH_HOST_KEY}" > known_hosts
    - ssh -v fwe@h2652485.stratoserver.net "echo test"
    - rsync -avuz -e 'ssh -i ~/.ssh/deploy_rsa.pub' backend fwe@h2652485.stratoserver.net:/home/fwe/passwordmanager/develop
  environment:
    name: develop
    url: https://dev.example.com
  only:
    - develop
