image: node:latest

cache:
  paths:
   - backend/node_modules/

before_script:
  - cd backend
  - npm install
  
stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo "Running tests"

build:
  stage: build
  script:
    - echo "Building the app"
    - cd ../frontend
    - npm install -g @angular/cli
    - npm install
    - ng build
    - cp -rv dist ../backend/frontend

deploy_develop:
  stage: deploy
  script:
    - echo "Deploy to develop server"
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
    - mkdir "${HOME}/.ssh"
    - cd "${HOME}/.ssh"
    - echo "${SSH_PRIVATE_KEY}" > id_rsa
    - chmod 700 id_rsa
    - echo "${SSH_HOST_KEY}" > known_hosts
    - cd "${CI_PROJECT_DIR}"
    - rsync -avz backend/ fwe@h2652485.stratoserver.net:/home/fwe/passwordmanager/develop
    - ssh -v fwe@h2652485.stratoserver.net "pm2 restart all"
  environment:
    name: develop
    url: http://h2652485.stratoserver.net:8080
  only:
    - develop
    
    
deploy_master:
  stage: deploy
  script:
    - echo "Deploy to master server"
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
    - mkdir "${HOME}/.ssh"
    - cd "${HOME}/.ssh"
    - echo "${SSH_PRIVATE_KEY}" > id_rsa
    - chmod 700 id_rsa
    - echo "${SSH_HOST_KEY}" > known_hosts
    - cd "${CI_PROJECT_DIR}"
    - rsync -avz backend/ fwe@h2652485.stratoserver.net:/home/fwe/passwordmanager/master
    - ssh -v fwe@h2652485.stratoserver.net "pm2 restart all"
  environment:
    name: master
    url: https://dev.example.com
  only:
    - master
