language: node_js
node_js:
  - "7"
  - "6"
  - "5"

cache:
  directories:
    - "frontend/node_modules"
    - "backend/node_modules"

services:
  - mongodb

install:
    - cd backend
    - npm install
    - cd ../frontend
    - npm install
    - cd ..

script:
    - cd backend
    - npm run lint

notifications:
    slack: laecherbar:y1NWyusbhnKv2tGC3XQCmmJW
