language: node_js
node_js:
  - "iojs"
  - "7"
  - "6"
  - "5"
  - "4"
  - "0"

cache:
  directories:
    - "frontend/node_modules"
    - "backend/node_modules"

install:
    - cd backend
    - npm install

script:
    - cd backend
    - npm test

notifications:
    slack: laecherbar:y1NWyusbhnKv2tGC3XQCmmJW
