language: node_js
node_js:
  - "7"
  - "6"

cache:
  directories:
    - "frontend/node_modules"
    - "backend/node_modules"

services:
  - mongodb

addons:
  firefox: "latest"

install:
    - cd backend
    - npm install
    - cd ../frontend
    - npm install
    - cd ..

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

jobs:
  include:
    - stage: test
      script:
        - cd frontend
        - npm run lint
        - npm test
        - cd ..
      script:
        - cd backend
        - npm run lint
        - cd ..
    - stage: deploy
      script: echo "deploy"

notifications:
    slack: laecherbar:y1NWyusbhnKv2tGC3XQCmmJW
