language: node_js
node_js:
  - "7"
  - "6"

branches:
  only:
  - master

cache:
  directories:
    - "frontend/node_modules"
    - "backend/node_modules"

services:
  - mongodb

addons:
  firefox: "latest"

install:
    - cd backend
    - npm install
    - cd ../frontend
    - npm install
    - cd ..

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
    - cd backend
    - npm run lint
    - cd ../frontend
    - npm run lint
    - npm test
    - ng build -e ${TRAVIS_BRANCH}
    - cp -rv dist ../backend
    - rm -r dist
    - ng build -e build
    - mv dist frontend
    - cp -rv frontend ../backend
    - cd ../backend
    - ls -lah

deploy:
  skip_cleanup: true

notifications:
    slack: laecherbar:y1NWyusbhnKv2tGC3XQCmmJW
