version: 2
jobs:
  buildBackend:
    docker:
      - image: circleci/node:7.10
      - image: mongo:3.4.4
    working_directory: ~/passwordManager
    parallelism: 2
    steps:
      - checkout
      - run: cd backend && npm install && ./node_modules/gulp/bin/gulp.js

  testFrontend:
    docker:
      - image: circleci/node:7.10
      - image: mongo:3.4.4
    working_directory: ~/passwordManager
    steps:
      - checkout
      - run: cd frontend && npm install && ./node_modules/@angular/cli/bin/ng lint

  buildFrontend:
    docker:
      - image: circleci/node:7.10
      - image: mongo:3.4.4
    working_directory: ~/passwordManager
    steps:
      - checkout
      - run: cd frontend && npm install && ./node_modules/@angular/cli/bin/ng build -e master

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - buildBackend
      - testFrontend
      - buildFrontend:
          requires:
            - testFrontend
